export {default as Bank} from './bank/bank'
export {default as Features} from './features/features'
export {default as Footer} from './footer/footer'
export {default as Header} from './header/header'
export {default as Possibility} from './possibility/possibility'
export {default as What} from './what/what'
export {default as BankHome} from './bank/bank.home'
export {default as BankFeatures} from './features/features.bank'